I=imread('Anger/1.jpg');
Face=facedetection(I);
figure,imshow(Face);
I=imread('Anger/5.jpg');
Face=facedetection(I);
figure,imshow(Face);
I=imread('Anger/9.jpg');
Face=facedetection(I);
figure,imshow(Face);